repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  name: sawtooth-giskard
  homepage: 
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true