# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.6'

services:

  giskard-engine:
    image: sawtooth-giskard-engine:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  giskard-cli:
    image: sawtooth-giskard-cli:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  giskard-common:
    image: sawtooth-giskard-common:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  giskard-core:
    image: sawtooth-giskard-core:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

  giskard-validator-registry:
    image: sawtooth-giskard-validator-registry-tp:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "

#  giskard-sgx:
#    image: sawtooth-giskard-sgx:${ISOLATION_ID}
#    volumes:
#      - ../build/debs:/build/debs
#    command: |
#      bash -c "
#        cp /tmp/*.deb /build/debs
#      "

#  giskard-simulator:
#    image: sawtooth-giskard-simulator:${ISOLATION_ID}
#    volumes:
#      - ../build/debs:/build/debs
#    command: |
#      bash -c "
#        cp /tmp/*.deb /build/debs
#      "
#  ias_client:
#    image: sawtooth-ias-client:${ISOLATION_ID}
#    volumes:
#      - ../build/debs:/build/debs
#    command: |
#      bash -c "
#        cp /tmp/*.deb /build/debs
#      "

#  ias_proxy:
#    image: sawtooth-ias-proxy:${ISOLATION_ID}
#    volumes:
#      - ../build/debs:/build/debs
#    command: |
#      bash -c "
#        cp /tmp/*.deb /build/debs
#      "

  giskard-tests:
    image: sawtooth-giskard-tests:${ISOLATION_ID}
    volumes:
      - ../build/debs:/build/debs
    command: |
      bash -c "
        cp /tmp/*.deb /build/debs
      "
